version: "3.8"
services:
  autoannouncements:
    build: .
    image: autoannouncements
    volumes:
      - ./data:/home/app_user/data
    stdin_open: true
    tty: true
    command: bash -c "python send.py"